Gdxdsd 4256 add new columns
bcgov/GDX-Analytics-microservice pull request #111
Opened 2022-06-22 22:40 UTC by veenupunyani

2022-06-22 23:49 UTC, mark-walle requested changes

2022-06-22 23:49 UTC, mark-walle commented on s3_to_redshift/README.md
> +- `"add_columns"`: a list containing the names and values for any additional column that is not present in the csv file provided
Also, further down in the README there's a schema describing the JSON structure for configuration files to follow (it's below the line reading "The structure of the config file should resemble the following"). Can you add this there?

It probably makes sense to put it between the "columns_lookup" and "dbtables_dictionaries" makes sense. E.g.:

```
[...]
  "columns_lookup": [String],
  "add_columns":{
    "<add_column_name_1>": String
  }
  "dbtables_dictionaries": [String],
[...]
```

2023-03-17 16:20 UTC, TaylorFries approved these changes

2023-03-17 18:50 UTC, TaylorFries approved these changes

2023-03-17 20:20 UTC, merged