Implement STDOUT Report Functionality in s3_to_sfts.py
bcgov/GDX-Analytics-microservice pull request #19
Opened 2021-05-12 23:50 UTC by lclarko

2021-05-13 00:15 UTC, mark-walle requested changes
@lclarko I've submitted some inline comments for your consideration.

2021-05-13 00:15 UTC, mark-walle commented on sfts/s3_to_sfts.py
>      subprocess.check_call(
We may want to change this `check_call` to `check_output` https://docs.python.org/3/library/subprocess.html#subprocess.check_output.

Capture the output somehow, like `output = subprocess.check_output(...)`, then shortly after you could log it: `logger.info(output)`. That ought to keep the cron report clean, while preserving any messaging we might want to have for later review.

The exception raised by `check_output` is the same `CalledProcessError` one, so there shouldn't be need to alter the `try ... except` block.

2021-05-13 00:15 UTC, mark-walle commented on sfts/s3_to_sfts.py
> +        stderr=subprocess.DEVNULL)
From https://docs.python.org/3/library/subprocess.html#subprocess.DEVNULL

> Special value that can be used as the stdin, stdout or stderr argument to Popen and indicates that the special file os.devnull will be used.

If the output is to the null device, I think we can't ever really review what the output was. Correct me if I'm wrong.

We want to keep the log of the output of the subprocess call somewhere for review.

2021-05-13 16:37 UTC, lclarko commented on sfts/s3_to_sfts.py
> +    if data['objects_failed_to_sfts'] or data['objects_not_processed']:
This is my favourite part

2021-05-13 18:12 UTC, mark-walle commented on sfts/s3_to_sfts.py
>      subprocess.check_call(
You've switched to `check_output`. Resolving this.

2021-05-13 19:39 UTC, mark-walle requested changes

2021-05-13 19:39 UTC, mark-walle commented on sfts/s3_to_sfts.py
> +    output = subprocess.check_output(
@lclarko `output` is a byte literal (see: https://docs.python.org/3/library/stdtypes.html#binary-sequence-types-bytes-bytearray-memoryview).

This results in logs that will be difficult to read at a glance:
```
INFO:__main__:2021-05-13 11:03:05,994:b'User GDXSFTSDEV signed on\n--> cd GCPE/Shared/gdxtest\n--> put ./tmp/test_pmrp_20200228_20200327_20200330T183405_part000.csv\nUpload complete. File ID 767097304\n125126 bytes sent in 1.94 seconds at 62.99 kB/s\n--> quit\n'
```
You'll see there that the output is prepended with `b`, confirming a byte literal.

There are flags for `subprocess.check_output` that should resolve this issue.

From https://docs.python.org/3/library/subprocess.html#frequently-used-arguments
> If text mode is not used, stdin, stdout and stderr will be opened as binary streams. No encoding or line ending conversion is performed.

Please try setting the `text` flag true. You might also need to set the `encoding` flag; I'm not sure.

2021-05-13 19:39 UTC, mark-walle commented on sfts/s3_to_sfts.py
> +    logger.info(output)
If you choose not to use an encoding flag on `subprocess.check_output` above, then you may alternatively decode this here.

Something like: `logger.info(output.decode('utf-8'))` would be a place to start.

2021-05-13 20:48 UTC, mark-walle requested changes
@lclarko you have modified the `Pipfile`. This means there would have been a new `Pipfile.lock` generated. Please commit that so in Production we can run `pipenv install --ignore-pipfile` and not cause a lockfile drift in Prod from what's in the main branch.

2021-05-17 16:08 UTC, mark-walle commented on sfts/s3_to_sfts.py
> +    output = subprocess.check_output(
decoding on log output instead.

2021-05-17 16:08 UTC, mark-walle approved these changes

2021-05-17 20:47 UTC, merged