Gdxdsd 3675 sfts non contiguous dates
bcgov/GDX-Analytics-microservice pull request #25
Opened 2021-06-11 21:23 UTC by lclarko

2021-06-11 21:26 UTC, lclarko commented on sfts/redshift_to_s3.py
> +if 'start_date' in config and 'end_date' in config and not dates:
This may seem unnecessary, though I included "and not date" with future unified JSON schemas in mind.

2021-06-11 21:28 UTC, lclarko commented on sfts/redshift_to_s3.py
> +    date_key = "_".join(dates)
This feels like the appropriate way to name these objects, with the requested dates as part of the object name. That said, if you pass a list of many individual dates in the config file, the object name would be very long.

2021-07-13 19:01 UTC, mark-walle requested changes
@lclarko please modify README.md to include explanatory use of the new `sql_parse_key` (`pmrp_qdata_dates`) as a second level bullet in line 139, similar to how an explanatory usage was provided for the `pmrp_qdata_dates` parse key.

2021-07-13 22:25 UTC, lclarko commented on sfts/redshift_to_s3.py
> +    query_string = query[:last_or_index] + "" + query[last_or_index+3:]
Good catch. No reason to be there.

2021-07-14 14:51 UTC, mark-walle approved these changes

2021-07-14 15:26 UTC, merged